### ISSUE TITLE
Instructions on preparing the 2D-3D-S dataset

### ISSUE THREAD

**Issue by blurgyy** [82magnolia/piccolo#1]
According to [their project repository](https://github.com/alexsax/2D-3D-Semantics#dataset-modalities), the original directory structure provided by the 2D-3D-S dataset is as follows:

```plain
README.md
/assets
  semantic_labels.json
  utils.py
/area_1
  /3d
    pointcloud.mat
    rgb.obj    # The raw 3d mesh with rgb textures
    rgb.mtl      # The textures for the raw 3d mesh
    semantic.obj # Semantically-tagged 3d mesh
    semantic.mtl # Tectures for semantic.obj
    /rgb_textures
      {uuid_{i}}.jpg  # Texture images for the rgb 3d mesh
  /data   # all of the generated data
    /pose
      camera_{uuid}__{room}_{i}_frame_{j}_domain__pose.json
    /rgb
      camera_{uuid}__{room}_{i}_frame_{j}_domain__rgb.png
    /depth
    /global_xyz
    /normal
    /semantic
    /semantic_pretty
  /pano    # equirectangular projections
    /pose
      camera_{uuid}__{room}_{i}_frame_equirectangular_domain__pose.json
    /rgb
    /depth
    /global_xyz
    /normal
    /semantic
    /semantic_pretty
  /raw     # Raw data from Matterport
    {uuid}_pose_{pitch_level}_{yaw_position}.txt # RT matrix for raw sensor
    {uuid}_intrinsics_{pitch_level}.txt      # Camera calibration for sensor at {pitch_level}
    {uuid}_i{pitch_level}_{yaw_position}.jpg # Raw RGB image from sensor
    {uuid}_d{pitch_level}_{yaw_position}.jpg # Raw depth image form sensor
/area_2
/area_3
/area_4
/area_5a
/area_5b
/area_6
```

While in the [dataset preparation](https://github.com/82magnolia/piccolo#dataset-preparation) section, the 2D-3D-S data for PICCOLO is organized otherwise.  After setting up the environment, to run on `area_3` of the 2D-3D-S dataset, I have tried the below steps:

1. Symlinking `area_3/data/rgb/` (in the original 2D-3D-S dataset) to `piccolo/data/stanford/pano/area_3`
2. Symlinking `area_3/data/raw/*.txt` (in the original 2D-3D-S dataset) under `piccolo/data/stanford/pcd_not_aligned/area_3` directory
3. Symlinking `area_3/pano/pose` (in the original 2D-3D-S dataset) to `piccolo/data/stanford/pose`

Then when I run `python main.py --config configs/stanford.ini --log log/test`, it gives the following traceback:

```python
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    localize.localize_stanford(cfg, writer, log_dir)
  File "/path/to/piccolo/localize.py", line 209, in localize_stanford
    xyz_np, rgb_np = data_utils.read_stanford(pcd_name, sample_rate)
  File "/path/to/piccolo/data_utils.py", line 35, in read_stanford
    data = read_table(filepath, header=None, delim_whitespace=True).values
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/path/to/.conda/envs/piccolo/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './data/stanford/pcd_not_aligned/area_3/WC_1.txt'
```

It seems that the code tries to load a file called `WC_1.txt` under `data/pcd_not_aligned` directory, while filenames in that directory typically look like `04a287849657478ea774727e5bff5202_pose_1_0.txt` and `04a287849657478ea774727e5bff5202_intrinsics_0.txt`.

Could you please point out anything missing in my dataset preparation steps?

**Comment by slothfulxtx** [comment]
Hi,

Thanks for the discussion. I've found a small mistake in [blurgyy](https://github.com/blurgyy)'s suggestions, and here's my solution. 

1.  Symlink area_3/pano/rgb/ (in the original 2D-3D-S dataset) to piccolo/data/stanford/pano/area_3

**Comment by 82magnolia** [comment]
Hello,

I deem that you are correct. Thans for the suggestion! I will update the README.md accordingly in due course.
